import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import useFibonacci from "~/hooks/useFibonacci";

const Home: NextPage = () => {
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState<{ user: string; message: string }[]>(
    []
  );
  const addStateToFibGame = useFibonacci((output: string) =>
    setMessages([...messages, { user: "system", message: output }])
  );
  const onAdd = () => {
    setMessages([...messages, { user: "user", message }]);
    addStateToFibGame(message);
    setMessage("");
  };

  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white  sm:text-[5rem]">
            Fibonacci guesser
          </h1>
          <p className=" text-white">Follow the prompts</p>

          <div className="mx-auto w-full max-w-3xl p-10 text-3xl text-white">
            {messages.map(({ message, user }) => (
              <div
                className={user === "user" ? "text-right" : "text-left"}
                key={message}
              >
                {message}
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>

          <div className=" flex content-between items-center">
            <input
              type="text"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              onSubmit={onAdd}
              className="w-full rounded-lg border-2 border-gray-300 p-5"
              placeholder="Message"
              onKeyDown={(e) => e.key === "Enter" && onAdd()}
            />
            <button className="btn-primary btn text-white" onClick={onAdd}>
              Ads
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
